{% set name = "ghq" %}
{% set version = "1.1.3" %}

package:
  name: go-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/x-motemen/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c251155a1b04ccd666a988f7746c0dcde8c64a9c2c6baf0824ee0ba4fb108771

build:
  number: 0
  script:
    - go install -ldflags "-X main.revision={{ version }}" .

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - ghq --help

about:
  home: https://github.com/x-motemen/ghq
  license: MIT
  license_file: LICENSE
  summary: ghq provides a way to organize remote repository clones, like go get does.

  dev_url: https://github.com/x-motemen/ghq

extra:
  recipe-maintainers:
    - sodre
